colorscheme blue
"colorscheme desert256
"colorscheme evening
"colorscheme inkpot
"colorscheme koehler
filetype on
"set columns=80
set dictionary=/usr/share/dict/american-english
set encoding=utf-8
set expandtab
"set foldcolumn=4
"set foldmethod=indent
"set foldmethod=syntax
set hlsearch
set incsearch
set number
set ruler
set shiftwidth=4
set softtabstop=4
set t_Co=256
set tabstop=4
set textwidth=80
set wildignore=*.o,*.bak,*~
source $VIMRUNTIME/ftplugin/man.vim
syntax on
